### PR TITLE
Created the Bank account Eligibility Checker App

### PR DESCRIPTION
**Pull request by Ayush21042002**
Using python with tkinter i have created the Bank account Eligibility Checker App for #1  with:
- Error checks in inputs
- if else for account eligibility checking
- output folder with some output screenshots

### CODE REVIEW

**Comment by AnshSSonkhia** [comment]
> Using python with tkinter i have created the Bank account Eligibility Checker App for #1 with:
> 
> * Error checks in inputs
> * if else for account eligibility checking
> * output folder with some output screenshots

Nice Work !!!
But, there is some mistake. Check the codes.
It is not taking any input.

**Comment by AnshSSonkhia** [comment]
> > Using python with tkinter i have created the Bank account Eligibility Checker App for #1 with:
> > 
> > * Error checks in inputs
> > * if else for account eligibility checking
> > * output folder with some output screenshots
> 
> Nice Work !!! But, there is some mistake. Check the codes. It is not taking any input.

Also, change the dimensions of the input boxes, so that they are in the middle of the screen. As , it looks elegant and systematic in middle.

**Comment by Ayush21042002** [comment]
> > Using python with tkinter i have created the Bank account Eligibility Checker App for #1 with:
> > 
> > * Error checks in inputs
> > * if else for account eligibility checking
> > * output folder with some output screenshots
> 
> Nice Work !!! But, there is some mistake. Check the codes. It is not taking any input.

When I am running it is taking the inputs correctly

https://user-images.githubusercontent.com/51852239/135750318-c784913d-ba85-44f5-bb0a-67c2a3bb3410.mp4

.

**Comment by Ayush21042002** [comment]
> > > Using python with tkinter i have created the Bank account Eligibility Checker App for #1 with:
> > > 
> > > * Error checks in inputs
> > > * if else for account eligibility checking
> > > * output folder with some output screenshots
> > 
> > 
> > Nice Work !!! But, there is some mistake. Check the codes. It is not taking any input.
> 
> Also, change the dimensions of the input boxes, so that they are in the middle of the screen. As , it looks elegant and systematic in middle.

image
Is this alright?
If this is ok then please tell then i will commit the changes.

**Comment by AnshSSonkhia** [comment]
> > > > Using python with tkinter i have created the Bank account Eligibility Checker App for #1 with:
> > > > 
> > > > * Error checks in inputs
> > > > * if else for account eligibility checking
> > > > * output folder with some output screenshots
> > > 
> > > 
> > > Nice Work !!! But, there is some mistake. Check the codes. It is not taking any input.
> > 
> > 
> > Also, change the dimensions of the input boxes, so that they are in the middle of the screen. As , it looks elegant and systematic in middle.
> 
> image Is this alright? If this is ok then please tell then i will commit the changes.

Yes Yes, This is Fantastic. You can go for it. Commit it.
I had added hacktoberfest-accepted label, if you want anything else, you can tell me.

**Comment by Ayush21042002** [comment]
> > > > > Using python with tkinter i have created the Bank account Eligibility Checker App for #1 with:
> > > > > 
> > > > > * Error checks in inputs
> > > > > * if else for account eligibility checking
> > > > > * output folder with some output screenshots
> > > > 
> > > > 
> > > > Nice Work !!! But, there is some mistake. Check the codes. It is not taking any input.
> > > 
> > > 
> > > Also, change the dimensions of the input boxes, so that they are in the middle of the screen. As , it looks elegant and systematic in middle.
> > 
> > 
> > image Is this alright? If this is ok then please tell then i will commit the changes.
> 
> Yes Yes, This is Fantastic. You can go for it. Commit it. I had added hacktoberfest-accepted label, if you want anything else, you can tell me.

Thank you, i have committed the changes so, if you can merge it would be helpful

**Review by AnshSSonkhia — APPROVED** [review]
Thanks for solving the issue.

**Pull request merged**
